Repository glu-lang/glu, pull requests merged in 2025-03, with the labels that each got.

#212 [Parser] Feature: Generate multiple ASTNode
  include/AST/ASTNode.hpp
  include/AST/Decl/ImportDecl.hpp
  include/AST/Decl/VarLetDecl.hpp
  include/AST/Expr/RefExpr.hpp
  include/AST/Types.hpp
  include/AST/Types/TypeKind.def
  include/AST/Types/TypeVariableTy.hpp
  include/Basic/SourceManager.hpp
  include/Parser/Parser.hpp
  lib/AST/HashType.cpp
  lib/Basic/SourceManager.cpp
  lib/Parser/CMakeLists.txt
  lib/Parser/Parser.yy
  test/Parser/Common.hpp
  test/Parser/Errors.cpp
  test/Parser/Expression.cpp
Labels: parser

#255 [Parser] Feature: Generate If & While & For Statements ASTNode in parser
  include/AST/Stmt/IfStmt.hpp
  lib/Parser/Parser.yy
  test/AST/ASTWalker.cpp
Labels: parser

#256 [Parser] Feature: Generate `StructDecl` ASTNode and create `PointerTy` ASTNode
  include/AST/Decl/StructDecl.hpp
  include/AST/Types/StructTy.hpp
  lib/Parser/Parser.yy
Labels: parser

#257 [Parser] Feature: add EnumDecl generation with this cases
  include/AST/Types/EnumTy.hpp
  lib/Parser/Parser.yy
Labels: parser

#260 [Bug] Fix: Add constistance in Hash and Equal visitors
  include/Basic/SourceLocation.hpp
  lib/AST/HashType.cpp
  test/AST/ASTContext.cpp
Labels: bug

#279 Feature: add `TypeBase *` in all Exprs in AST
  include/AST/ASTNode.hpp
  include/AST/Expr/LiteralExpr.hpp
Labels: sema

#261 [Bug] Fix/ refactor FunctionTy to use llvm::TrailingObjects for parameters
  include/AST/Types/FunctionTy.hpp
  include/Basic/InternedMemoryArena.hpp
  include/Basic/TypedMemoryArena.hpp
Labels: bug

#284 [Parser] Feature: Generate ParamDecl, FunctionDecl and TernaryExpr ASTNode in Parser
  include/AST/Decl/FunctionDecl.hpp
  include/AST/Types.hpp
  include/AST/Types/TypeKind.def
  include/AST/Types/VoidTy.hpp
  lib/Parser/Parser.yy
  test/AST/Decl/FunctionDecl.cpp
Labels: parser

#151 [DevOps] Continuous integration
  .github/workflows/linux_smoke-tests.yml
Labels: devops

#289 [Bug] Fix: uncomment Kind that are implemented
  include/GIL/InstKind.def
  include/GIL/Instructions/IntZextInst.hpp
Labels: bug

#287 [DevOps] CI: Linux Smoke Tests
  .github/workflows/linux_smoke-tests.yml
  CMakeLists.txt
Labels: devops
